config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  resources :posts, param: :slug
  resource :sessions, only: %i[new create destroy]
  resources :tags

  namespace :api do
    resource :auth, only: [:create]
    resources :places do
      resources :checkins, shallow: true
    end
    resources :checkins, only: [:index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/checkin.rb
class Checkin < ApplicationRecord
  belongs_to :place

  validates_presence_of :time_zone
  validate :time_zone_exists

  private

  def time_zone_exists
    return if time_zone? && ActiveSupport::TimeZone[time_zone].present?

    errors.add(:time_zone, 'does not exist')
  end
end

app/models/place.rb
class Place < ApplicationRecord
  acts_as_mappable distance_field_name: :distance,
                   lat_column_name: :latitude,
                   lng_column_name: :longitude

  has_many :checkins

  validates :name, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :slug, presence: true, uniqueness: true
  validates :body, presence: true
  validates :date, presence: true

  has_many :taggings
  has_many :tags, through: :taggings

  def to_param
    slug
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates_presence_of :name

  has_many :taggings
  has_many :posts, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_secure_token

  validates :email, presence: true, uniqueness: true
end

app/controllers/api/auths_controller.rb
class Api::AuthsController < ApiController
  skip_before_action :authenticate

  def create
    user = User.find_by(email: params[:email])

    if user&.authenticate(params[:password])
      render json: { token: user.token }, status: :ok
    else
      render json: { error: 'Datos incorrectos' }, status: :unprocessable_entity
    end
  end
end

app/controllers/api/checkins_controller.rb
class Api::CheckinsController < ApiController
  def index
    @checkins = if params[:place_id]
                  Place.find(params[:place_id]).checkins.order(datetime: :desc)
                else
                  Checkin.includes(:place).order(datetime: :desc)
                end
  end

  def show
    @checkin = Checkin.find(params[:id])
  end

  def create
    checkin_data = checkin_params
    checkin_data[:datetime] = ActiveSupport::TimeZone[checkin_params[:time_zone]].parse(checkin_params[:datetime])

    @place = Place.find(params[:place_id])
    @checkin = @place.checkins.new(checkin_data)

    if @checkin.save
      render json: @checkin, status: :created, location: api_checkin_url(@checkin)
    else
      render json: @checkin.errors.full_messages, status: :unprocessable_entity
    end
  end

  private

  def checkin_params
    params.require(:checkin).permit(:datetime, :latitude, :longitude, :notes, :time_zone)
  end
end

app/controllers/api/places_controller.rb
class Api::PlacesController < ApiController
  before_action :set_place, only: %i[show update destroy]

  def index
    @places = Place
              .select('id', 'name', 'latitude', 'longitude', 'notes')
              .by_distance(origin: [params[:latitude], params[:longitude]])

    render json: @places
  end

  def show
    render json: @place
  end

  def create
    @place = Place.new(place_params)

    if @place.save
      render json: @place, status: :created, location: api_places_url(@place)
    else
      render json: @place.errors, status: :unprocessable_entity
    end
  end

  def update
    if @place.update(place_params)
      render json: @place
    else
      render json: @place.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @place.destroy
  end

  private

  def place_params
    params.require(:place).permit(:name, :longitude, :latitude, :notes)
  end

  def set_place
    @place = Place.find(params[:id])
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  protect_from_forgery with: :null_session

  before_action :authenticate

  private

  def authenticate
    authenticate_or_request_with_http_token do |token, _options|
      User.find_by(token: token)
    end
  end

  def current_user
    @current_user ||= authenticate
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def authorize
    redirect_to new_sessions_path unless current_user
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authorize, only: [:new, :create, :edit, :update, :destroy]

  def index
    posts = Post.all

    if !current_user
      posts = posts.where(draft: false)
    end

    @posts = posts.order(date: :desc)
  end

  def show
    @post = Post.includes(:tags).find_by(slug: params[:slug])

    if @post.draft? && !current_user
      redirect_to root_path
    end
  end

  def new
    @post = Post.new
    @tags = Tag.all
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to posts_path, notice: "Post añadido correctamente."
    else
      render "new"
    end
  end

  def edit
    @post = Post.find_by(slug: params[:slug])
    @tags = Tag.all
  end

  def update
    @post = Post.find_by(slug: params[:slug])

    if @post.update(post_params)
      redirect_to posts_path, notice: "Post actualizado correctamente."
    else
      render "edit"
    end
  end

  def destroy
  end

  private

  def post_params
    params.require(:post).permit(:body, :date, :draft, :slug, :title, tag_ids: [])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to root_path if current_user
  end

  def create
    user = User.find_by(email: params[:email])

    if user&.authenticate(params[:password])
      session[:user_id] = user.id.to_s

      redirect_to root_path, notice: 'Te has conectado correctamente.'
    else
      redirect_to new_sessions_path, alert: 'Datos incorrectos.'
    end
  end

  def destroy
    session.delete(:user_id)

    redirect_to root_path, notice: 'Desconectado correctamente'
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authorize

  def index
    @tags = Tag.all
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tags_params)

    if @tag.save
      redirect_to tags_path, notice: "Etiqueta añadida correctamente."
    else
      render "new"
    end
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def update
    @tag = Tag.find(params[:id])

    if @tag.update(tags_params)
      redirect_to tags_path, notice: "Etiqueta editada correctamente."
    else
      render "edit"
    end
  end

  private

  def tags_params
    params.require(:tag).permit(:name)
  end
end

app/helpers/api/auths_helper.rb
module Api::AuthsHelper
end

app/helpers/api/checkins_helper.rb
module Api::CheckinsHelper
end

app/helpers/api/places_helper.rb
module Api::PlacesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
  <div class="flash__error">
    <ul>
      <% @post.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: @post do |form| %>
  <div class="form__control">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="form__control">
    <%= form.label :slug %>
    <%= form.text_field :slug %>
  </div>

  <div class="form__control">
    <%= form.label :body %>
    <%= form.text_area :body, rows: 20 %>
  </div>

  <div class="form__control">
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <div class="form__control form__control--checkbox">
    <%= form.label :draft %>
    <%= form.check_box :draft %>
  </div>

  <div class="form__control form__control--checkbox">
    <%= form.label :tags %><br />
    <%= form.collection_check_boxes :tag_ids, Tag.all, :id, :name %>
  </div>

  <%= form.submit %>
<% end %>

app/views/posts/edit.html.erb
<h1>Editar post</h1>

<%= render partial: "form" %>

app/views/posts/index.html.erb
<% if @posts.any? %>
  <ul>
    <% @posts.each do |post| %>
      <li>
        <small><%= post.date.strftime("%d-%m-%y") %></small>
        <%= link_to post.title, post_path(post) %>
        <% if post.draft? %>
        <small>draft</small>
        <% end %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>Todavía no hay ningún post en el blog.</p>
<% end %>

app/views/posts/new.html.erb
<h1>Add new post</h1>

<%= render partial: "form" %>

app/views/posts/show.html.erb
<article>
  <header>
    <h1><%= @post.title %></h1>
    <time datetime="<%= @post.date %>"><%= @post.date.strftime("%d-%m-%Y") %></time>
    #
    <%= render partial: "tags/list", locals: { tags: @post.tags } %>
    <% if current_user %>
      <%= link_to "Editar", edit_post_path(@post) %>
    <% end %>
  </header>

  <%= @post.body.html_safe %>
</article>

app/views/tags/_form.html.erb
<%= form_with model: @tag do |form| %>
  <div class="form__control">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <%= form.submit %>
<% end %>

app/views/tags/_list.html.erb
<%= tags.pluck(:name).join(", ") %>

app/views/tags/edit.html.erb
<h1>Editar etiqueta</h1>

<%= render partial: "form" %>

app/views/tags/index.html.erb
<h1>Etiquetas</h1>

<p><%= link_to "Añadir etiqueta", new_tag_path %></p>

<% if @tags.any? %>
  <ul>
    <% @tags.each do |tag| %>
      <li><%= link_to tag.name, edit_tag_path(tag) %></li>
    <% end %>
  </ul>
<% else %>
  <p>Todavía no hay etiquetas.</p>
<% end %>

app/views/tags/new.html.erb
<h1>Añadir etiqueta</h1>

<%= render partial: "form" %>